### ISSUE TITLE
现在是不能用了吗？

### ISSUE THREAD

**Issue by imdingji** [sunflo/smzdm_sign_bot#6]
安装的最新青龙面板2.8，貌似执行出错，python3的问题？

**Comment by sunflo** [comment]
好用的。

**Comment by imdingji** [comment]
我的库拉成功了，但是只要一执行就报错，请问是什么原因，感谢！
## 开始执行... 2022-01-05 17:18:01

[2022-01-05 17:18:02]: 检测到1个cookie记录
开始签到
Traceback (most recent call last):
  File "smzdm_auto_sign_bot.py", line 223, in <module>
    result = bot.checkin()
  File "smzdm_auto_sign_bot.py", line 209, in checkin
    msg = self.session.get(SIGN_URL)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/usr/lib/python3.8/http/client.py", line 1225, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 770-772: ordinal not in range(256)

## 执行结束... 2022-01-05 17:18:02 耗时 1 秒

**Comment by sunflo** [comment]
推测是cookie太长导致的，cookie填如下信息就够了。userCookie = "sess=xxxxxx; user=user:xxx|xxx; smzdm_id=xxx;"

**Comment by imdingji** [comment]
给力，可以了！！
